- name: Install OpenLDAP
  hosts: ldap
  become: true
  vars_files:
    - group_vars/secrets.yml
  roles:
    - openldap_server
    # - web_ui
    - { role: lam, when: lam.enabled == True }
    - { role: newrelic, when: newrelic.enabled == True }

  handlers:

  - name: restart slapd
    service: name=slapd state=restarted enabled=yes
