- name: Install OpenLDAP
  hosts: ldap
  become: true
  vars_files:
    - group_vars/secrets.yml
  roles:
    - openldap_server
    # - web_ui
    - newrelic

  handlers:
  - name: restart apache
    service: name=apache2 state=restarted

  - name: restart slapd
    service: name=slapd state=restarted enabled=yes
