- hosts: vagrant_ldap
  become: true
  roles:
  - role: openldap_server
    openldap_server_domain_name: ubuntunet.net
    openldap_server_rootpw: jk66Wd8x
    openldap_server_enable_ssl: false
    # openldap_server_country: MW
    # openldap_server_location: Lilongwe
    # openldap_server_organization: UbuntuNet Alliance