
- name: Copy the example entries
  template: src=persons.ldif.j2 dest=/tmp/persons.ldif

- name: Add some example entries
  shell: >
    ldapadd -x -c -D "cn=Manager,{{ openldap_server_base_dn }}" -w {{ openldap_server_rootpw }} -f '/tmp/persons.ldif' && touch /root/.entriesadded
  args:
    creates: /root/.entriesadded
